import Config

config :sonos_elixir, Sonos.Repo,
  database: "priv/db.sqlite3",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 3

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
#

config :sonos_elixir, SonosWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # http: [ip: {127, 0, 0, 1}, port: 4000],
  http: [
    ip:
      System.get_env("HOST", "0.0.0.0")
      |> String.split(".")
      |> Enum.map(fn x ->
        x
        |> String.to_integer()
      end)
      |> List.to_tuple(),
    port:
      System.get_env("PORT", "4000")
      |> String.to_integer()
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "VNZtGlQkgl7nyBaHYRKmfGF2WuNlQNkcEL/KFBzuoU2iWzbe83uoDgrPCwzT1oLe",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sonos_elixir, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sonos_elixir, ~w(--watch)]}
  ]

# TODO live code reloading

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :sonos_elixir, SonosWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/sonos_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :sonos_elixir, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"
config :logger, :console, truncate: :infinity

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# config :big_brother_ex, :reload_config,
#  reloader: BigBrother.FS.Reloader,
#  debounce: 1000,
#  patterns: [
#    ~r"lib/.*(ex)$"
#  ]
